version: '3.9'

services:
  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ../../../data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stc
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432